version: '3'
services:
  app: 
    build: .
    container_name: wallet_api
    ports:
      - 8089:80
    volumes: 
     - ./:/app
  db:
    image: postgres
    restart: always
    container_name: wallet-api-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - 5433:5432

