name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: make setup
      - name: Run tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          make test
          vendor/bin/php-coveralls --coverage_clover=./.phpunit/coverage-clover.xmls -v
